"""empty message

Revision ID: a46ea41d2614
Revises: 7301a88308d0
Create Date: 2022-10-30 10:54:58.719137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46ea41d2614'
down_revision = '7301a88308d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('contato', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('salario', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('vaga', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'vaga')
    op.drop_column('posts', 'salario')
    op.drop_column('posts', 'contato')
    # ### end Alembic commands ###
