"""empty message

Revision ID: e2c8afd7e8af
Revises: a46ea41d2614
Create Date: 2022-11-03 10:44:51.003646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c8afd7e8af'
down_revision = 'a46ea41d2614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comment')
    # ### end Alembic commands ###
